version: "3.5"

services:
  nats:
    image: nats
    ports:
      - "8222:8222"
      - "4222:4222"
    networks: ["nats"]
    command: "--http_port 8222 -js"
    restart: unless-stopped

networks:
  nats:
    name: nats