version: '3'
services:
  mongodb1:
    image: mongo:latest # Use the desired version of MongoDB
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db
      - ./keyfile:/opt/keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    command: "--replSet rs0 --bind_ip_all --keyFile /opt/keyfile/keyfile"
    networks:
      - mongo-cluster

  mongodb2:
    image: mongo:latest
    container_name: mongodb2
    ports:
      - "27018:27017"
    volumes:
      - mongodb2_data:/data/db
      - ./keyfile:/opt/keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    command: "--replSet rs0 --bind_ip_all --keyFile /opt/keyfile/keyfile"
    networks:
      - mongo-cluster

  mongodb3:
    image: mongo:latest
    container_name: mongodb3
    ports:
      - "27019:27017"
    volumes:
      - mongodb3_data:/data/db
      - ./keyfile:/opt/keyfile
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=adminpassword
    command: "--replSet rs0 --bind_ip_all --keyFile /opt/keyfile/keyfile"
    networks:
      - mongo-cluster

networks:
  mongo-cluster:
    driver: bridge

volumes:
  mongodb1_data:
    driver: local
  mongodb2_data:
    driver: local
  mongodb3_data:
    driver: local


  rs.initiate({
_id: "rs0",
members: [
  { _id: 0, host: "mongodb1:27017" },
  { _id: 1, host: "mongodb2:27017" },
  { _id: 2, host: "mongodb2:27017" },
]
})
