version: '3.8'

services:
  mongodb1:
    image: shikho/mongodb:7.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb1
    restart: unless-stopped
    networks:
      - mongoCluster
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb1-data:/data/db
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfile

  mongodb2:
    image: shikho/mongodb:7.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb2
    restart: unless-stopped
    networks:
      - mongoCluster
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb2-data:/data/db
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfile

  mongodb3:
    image: shikho/mongodb:7.0
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mongodb3
    restart: unless-stopped
    networks:
      - mongoCluster
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=secret
    volumes:
      - mongodb3-data:/data/db
    command: mongod --replSet rs0 --bind_ip_all --keyFile /opt/keyfile

networks:
  mongoCluster:

volumes:
  mongodb1-data:
  mongodb2-data:
  mongodb3-data: