version: '3.5'

services:
  arangodb:
    container_name: arangodb_container
    platform: linux/x86_64
    image: arangodb/enterprise:3.9.0-noavx
    environment:
      ARANGO_ROOT_PASSWORD: ${ARANGODB_ROOT_PASSWORD:-admin}
    volumes:
      - arangodb:/var/lib/arangodb3
    ports:
      - "8529:8529"
    networks:
      - arangodb
    restart: unless-stopped

networks:
  arangodb:
    driver: bridge

volumes:
  arangodb: