version: "3.8"

services:
  redis:
    image: redis/redis-stack:latest
    container_name: redis-with-search
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    environment:
      - REDIS_ARGS=--requirepass admin
volumes:
  redis_data:
