version: '3.5'

services:
  redis:
    container_name: redis_container
    image: bitnami/redis:latest
    environment:
      REDIS_PASSWORD: ${REDIS_PASSWORD:-admin}
      MODULES_LOAD: /usr/lib/redis/modules/redisearch.so
    volumes:
      - redis:/bitnami/redis/data
    ports:
      - "6379:6379"
    networks:
      redis:
    restart: unless-stopped

networks:
  redis:
    driver: bridge

volumes:
  redis: